// <auto-generated />
using System;
using AM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AM.Infrastructure.Migrations
{
    [DbContext(typeof(R1Context))]
    [Migration("20250407212912_LaboOuerfelliMohamed")]
    partial class LaboOuerfelliMohamed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AM.ApplicationCore.Domain.Analyse", b =>
                {
                    b.Property<int>("AnalyseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalyseId"));

                    b.Property<int>("BilanCodeInfirmier")
                        .HasColumnType("int");

                    b.Property<int>("BilanCodePatient")
                        .HasColumnType("int");

                    b.Property<DateTime>("BilanDatePrelevement")
                        .HasColumnType("datetime2");

                    b.Property<int>("DureeResultat")
                        .HasColumnType("int");

                    b.Property<double>("PrixAnalyse")
                        .HasColumnType("float");

                    b.Property<string>("TypeAnalyse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValeurAnalyse")
                        .HasColumnType("real");

                    b.Property<float>("ValeurMaxNormale")
                        .HasColumnType("real");

                    b.Property<float>("ValeurMinNormale")
                        .HasColumnType("real");

                    b.HasKey("AnalyseId");

                    b.HasIndex("BilanCodeInfirmier", "BilanCodePatient", "BilanDatePrelevement");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Bilan", b =>
                {
                    b.Property<int>("CodeInfirmier")
                        .HasColumnType("int");

                    b.Property<int>("CodePatient")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePrelevement")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailMedecin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Paye")
                        .HasColumnType("bit");

                    b.HasKey("CodeInfirmier", "CodePatient", "DatePrelevement");

                    b.HasIndex("CodePatient");

                    b.ToTable("Bilans");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Infirmier", b =>
                {
                    b.Property<int>("InfirmierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfirmierId"));

                    b.Property<int>("LaboratoireId")
                        .HasColumnType("int");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("specialite")
                        .HasColumnType("int");

                    b.HasKey("InfirmierId");

                    b.HasIndex("LaboratoireId");

                    b.ToTable("Infirmiers");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Laboratoire", b =>
                {
                    b.Property<int>("LaboratoireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaboratoireId"));

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AdresseLabo");

                    b.HasKey("LaboratoireId");

                    b.ToTable("Laboratoires");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Patient", b =>
                {
                    b.Property<int>("CodePatient")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodePatient"));

                    b.Property<string>("EmailPatient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Informations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodePatient");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("InfirmierPatient", b =>
                {
                    b.Property<int>("InfirmiersInfirmierId")
                        .HasColumnType("int");

                    b.Property<int>("PatientsCodePatient")
                        .HasColumnType("int");

                    b.HasKey("InfirmiersInfirmierId", "PatientsCodePatient");

                    b.HasIndex("PatientsCodePatient");

                    b.ToTable("InfirmierPatient");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Analyse", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Bilan", "Bilan")
                        .WithMany("Analyses")
                        .HasForeignKey("BilanCodeInfirmier", "BilanCodePatient", "BilanDatePrelevement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bilan");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Bilan", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Infirmier", "Infirmier")
                        .WithMany()
                        .HasForeignKey("CodeInfirmier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AM.ApplicationCore.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("CodePatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Infirmier");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Infirmier", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Laboratoire", "Laboratoire")
                        .WithMany("Infirmiers")
                        .HasForeignKey("LaboratoireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratoire");
                });

            modelBuilder.Entity("InfirmierPatient", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Infirmier", null)
                        .WithMany()
                        .HasForeignKey("InfirmiersInfirmierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AM.ApplicationCore.Domain.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsCodePatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Bilan", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Laboratoire", b =>
                {
                    b.Navigation("Infirmiers");
                });
#pragma warning restore 612, 618
        }
    }
}
